### ISSUE TITLE
Package limits

### ISSUE THREAD

**Issue by Dexxa1024** [jsmcm/WebCP#1]
Package limits dont seem to be working,  created a package, user and domain,  with unlimited features and everytime try to add wordpress all its saying is ERROR, you have no more MySQL databases left. Install cannot continue

**Comment by Dexxa1024** [comment]
Thats on the user panel side

**Comment by jsmcm** [comment]
Thanks, will take a look at that. It should work if you set a large number, but will check in why its not working when you try to set an  unlimited amount.

**Comment by jsmcm** [comment]
Issue Fixed
